export interface ThemePreset {
    id: string;
    name: string;
    description: string;
    isDark: boolean;
    colors: Record<string, string>;
    preview: {
        header: string;
        sidebar: string;
        chatBg: string;
        bubbleOut: string;
        bubbleIn: string;
        accent: string;
    };
    messageBubbles: {
        outgoingColor: string;
        incomingColor: string;
        outgoingTextColor: string;
        incomingTextColor: string;
    };
}

export const THEME_PRESETS: ThemePreset[] = [
    {
        id: 'classic',
        name: 'Classic',
        description: 'Rumker по умолчанию',
        isDark: false,
        preview: {
            header: '#5a8a9a',
            sidebar: '#ffffff',
            chatBg: '#f5f6f8',
            bubbleOut: '#EFFDDE',
            bubbleIn: '#ffffff',
            accent: '#4a7c59',
        },
        messageBubbles: {
            outgoingColor: '#EFFDDE',
            incomingColor: '#FFFFFF',
            outgoingTextColor: '#2d3748',
            incomingTextColor: '#2d3748',
        },
        colors: {
            '--background': '#f5f6f8',
            '--foreground': '#2d3748',
            '--card': '#ffffff',
            '--card-foreground': '#2d3748',
            '--popover': '#ffffff',
            '--popover-foreground': '#2d3748',
            '--primary': '#4a7c59',
            '--primary-foreground': '#ffffff',
            '--secondary': '#e8ecef',
            '--secondary-foreground': '#4a5568',
            '--muted': '#e2e8f0',
            '--muted-foreground': '#718096',
            '--accent': '#edf2f7',
            '--accent-foreground': '#2d3748',
            '--destructive': '#e53e3e',
            '--border': '#cbd5e0',
            '--input': '#e2e8f0',
            '--ring': '#4a7c59',
            '--sidebar': '#f7fafc',
            '--sidebar-foreground': '#2d3748',
            '--sidebar-primary': '#4a7c59',
            '--sidebar-primary-foreground': '#ffffff',
            '--sidebar-accent': '#e8ecef',
            '--sidebar-accent-foreground': '#2d3748',
            '--sidebar-border': '#e2e8f0',
            '--sidebar-ring': '#4a7c59',
            '--tg-primary': '#4a7c59',
            '--tg-secondary': '#5a8a9a',
            '--tg-bg': '#f5f6f8',
            '--tg-bg-dark': '#1a202c',
            '--tg-message-out': '#EFFDDE',
            '--tg-message-in': '#ffffff',
            '--tg-text': '#2d3748',
            '--tg-text-secondary': '#718096',
            '--tg-divider': '#e2e8f0',
            '--tg-online': '#48bb78',
            '--tg-link': '#4a7c59',
            '--tg-hover': '#edf2f7',
            '--tg-active-chat': '#4a7c59',
            '--tg-input-bg': '#edf2f7',
            '--tg-header': '#5a8a9a',
        },
    },
    {
        id: 'ocean',
        name: 'Ocean',
        description: 'Telegram-стиль',
        isDark: false,
        preview: {
            header: '#3390ec',
            sidebar: '#ffffff',
            chatBg: '#edf2f7',
            bubbleOut: '#effdde',
            bubbleIn: '#ffffff',
            accent: '#3390ec',
        },
        messageBubbles: {
            outgoingColor: '#effdde',
            incomingColor: '#ffffff',
            outgoingTextColor: '#2d3748',
            incomingTextColor: '#2d3748',
        },
        colors: {
            '--background': '#edf2f7',
            '--foreground': '#2d3748',
            '--card': '#ffffff',
            '--card-foreground': '#2d3748',
            '--popover': '#ffffff',
            '--popover-foreground': '#2d3748',
            '--primary': '#3390ec',
            '--primary-foreground': '#ffffff',
            '--secondary': '#e8ecef',
            '--secondary-foreground': '#4a5568',
            '--muted': '#e2e8f0',
            '--muted-foreground': '#718096',
            '--accent': '#edf2f7',
            '--accent-foreground': '#2d3748',
            '--destructive': '#e53e3e',
            '--border': '#cbd5e0',
            '--input': '#e2e8f0',
            '--ring': '#3390ec',
            '--sidebar': '#ffffff',
            '--sidebar-foreground': '#2d3748',
            '--sidebar-primary': '#3390ec',
            '--sidebar-primary-foreground': '#ffffff',
            '--sidebar-accent': '#e8f4fd',
            '--sidebar-accent-foreground': '#2d3748',
            '--sidebar-border': '#e2e8f0',
            '--sidebar-ring': '#3390ec',
            '--tg-primary': '#3390ec',
            '--tg-secondary': '#3390ec',
            '--tg-bg': '#edf2f7',
            '--tg-bg-dark': '#1a202c',
            '--tg-message-out': '#effdde',
            '--tg-message-in': '#ffffff',
            '--tg-text': '#2d3748',
            '--tg-text-secondary': '#718096',
            '--tg-divider': '#e2e8f0',
            '--tg-online': '#4dc862',
            '--tg-link': '#3390ec',
            '--tg-hover': '#e8f4fd',
            '--tg-active-chat': '#3390ec',
            '--tg-input-bg': '#f0f2f5',
            '--tg-header': '#3390ec',
        },
    },
    {
        id: 'midnight',
        name: 'Midnight',
        description: 'Тёмная с фиолетовым',
        isDark: true,
        preview: {
            header: '#1a1a2e',
            sidebar: '#16162a',
            chatBg: '#0f0f1a',
            bubbleOut: '#3b2d6b',
            bubbleIn: '#232340',
            accent: '#a78bfa',
        },
        messageBubbles: {
            outgoingColor: '#3b2d6b',
            incomingColor: '#232340',
            outgoingTextColor: '#e2e0f0',
            incomingTextColor: '#d0cde0',
        },
        colors: {
            '--background': '#0f0f1a',
            '--foreground': '#e2e0f0',
            '--card': '#1a1a2e',
            '--card-foreground': '#e2e0f0',
            '--popover': '#1a1a2e',
            '--popover-foreground': '#e2e0f0',
            '--primary': '#a78bfa',
            '--primary-foreground': '#0f0f1a',
            '--secondary': '#2a2a4a',
            '--secondary-foreground': '#c4c0d8',
            '--muted': '#2a2a4a',
            '--muted-foreground': '#8886a0',
            '--accent': '#232340',
            '--accent-foreground': '#e2e0f0',
            '--destructive': '#f87171',
            '--border': 'rgba(167, 139, 250, 0.15)',
            '--input': 'rgba(167, 139, 250, 0.12)',
            '--ring': '#a78bfa',
            '--sidebar': '#16162a',
            '--sidebar-foreground': '#e2e0f0',
            '--sidebar-primary': '#a78bfa',
            '--sidebar-primary-foreground': '#0f0f1a',
            '--sidebar-accent': '#2a2a4a',
            '--sidebar-accent-foreground': '#e2e0f0',
            '--sidebar-border': 'rgba(167, 139, 250, 0.1)',
            '--sidebar-ring': '#a78bfa',
            '--tg-primary': '#a78bfa',
            '--tg-secondary': '#818cf8',
            '--tg-bg': '#0f0f1a',
            '--tg-bg-dark': '#0a0a14',
            '--tg-message-out': '#3b2d6b',
            '--tg-message-in': '#232340',
            '--tg-text': '#e2e0f0',
            '--tg-text-secondary': '#8886a0',
            '--tg-divider': 'rgba(167, 139, 250, 0.1)',
            '--tg-online': '#4ade80',
            '--tg-link': '#a78bfa',
            '--tg-hover': '#232340',
            '--tg-active-chat': '#3b2d6b',
            '--tg-input-bg': '#1a1a2e',
            '--tg-header': '#1a1a2e',
        },
    },
    {
        id: 'rose',
        name: 'Rose',
        description: 'Тёплый розовый',
        isDark: false,
        preview: {
            header: '#e8788a',
            sidebar: '#ffffff',
            chatBg: '#fdf2f4',
            bubbleOut: '#fce4ec',
            bubbleIn: '#ffffff',
            accent: '#e8788a',
        },
        messageBubbles: {
            outgoingColor: '#fce4ec',
            incomingColor: '#ffffff',
            outgoingTextColor: '#4a3035',
            incomingTextColor: '#4a3035',
        },
        colors: {
            '--background': '#fdf2f4',
            '--foreground': '#4a3035',
            '--card': '#ffffff',
            '--card-foreground': '#4a3035',
            '--popover': '#ffffff',
            '--popover-foreground': '#4a3035',
            '--primary': '#e8788a',
            '--primary-foreground': '#ffffff',
            '--secondary': '#fce4ec',
            '--secondary-foreground': '#6b4049',
            '--muted': '#f5d5da',
            '--muted-foreground': '#9a6b73',
            '--accent': '#fdf2f4',
            '--accent-foreground': '#4a3035',
            '--destructive': '#e53e3e',
            '--border': '#f0c0ca',
            '--input': '#f5d5da',
            '--ring': '#e8788a',
            '--sidebar': '#ffffff',
            '--sidebar-foreground': '#4a3035',
            '--sidebar-primary': '#e8788a',
            '--sidebar-primary-foreground': '#ffffff',
            '--sidebar-accent': '#fce4ec',
            '--sidebar-accent-foreground': '#4a3035',
            '--sidebar-border': '#f5d5da',
            '--sidebar-ring': '#e8788a',
            '--tg-primary': '#e8788a',
            '--tg-secondary': '#f0a0b0',
            '--tg-bg': '#fdf2f4',
            '--tg-bg-dark': '#2a1015',
            '--tg-message-out': '#fce4ec',
            '--tg-message-in': '#ffffff',
            '--tg-text': '#4a3035',
            '--tg-text-secondary': '#9a6b73',
            '--tg-divider': '#f5d5da',
            '--tg-online': '#48bb78',
            '--tg-link': '#e8788a',
            '--tg-hover': '#fce4ec',
            '--tg-active-chat': '#e8788a',
            '--tg-input-bg': '#fdf2f4',
            '--tg-header': '#e8788a',
        },
    },
    {
        id: 'sunset',
        name: 'Sunset',
        description: 'Оранжевый и тёплый',
        isDark: false,
        preview: {
            header: '#e67e22',
            sidebar: '#ffffff',
            chatBg: '#fdf6ec',
            bubbleOut: '#fef3c7',
            bubbleIn: '#ffffff',
            accent: '#e67e22',
        },
        messageBubbles: {
            outgoingColor: '#fef3c7',
            incomingColor: '#ffffff',
            outgoingTextColor: '#4a3520',
            incomingTextColor: '#4a3520',
        },
        colors: {
            '--background': '#fdf6ec',
            '--foreground': '#4a3520',
            '--card': '#ffffff',
            '--card-foreground': '#4a3520',
            '--popover': '#ffffff',
            '--popover-foreground': '#4a3520',
            '--primary': '#e67e22',
            '--primary-foreground': '#ffffff',
            '--secondary': '#fde8c8',
            '--secondary-foreground': '#6b4a25',
            '--muted': '#f5e0c0',
            '--muted-foreground': '#9a7a50',
            '--accent': '#fdf6ec',
            '--accent-foreground': '#4a3520',
            '--destructive': '#e53e3e',
            '--border': '#f0d0a0',
            '--input': '#f5e0c0',
            '--ring': '#e67e22',
            '--sidebar': '#ffffff',
            '--sidebar-foreground': '#4a3520',
            '--sidebar-primary': '#e67e22',
            '--sidebar-primary-foreground': '#ffffff',
            '--sidebar-accent': '#fde8c8',
            '--sidebar-accent-foreground': '#4a3520',
            '--sidebar-border': '#f5e0c0',
            '--sidebar-ring': '#e67e22',
            '--tg-primary': '#e67e22',
            '--tg-secondary': '#f0a050',
            '--tg-bg': '#fdf6ec',
            '--tg-bg-dark': '#2a1a08',
            '--tg-message-out': '#fef3c7',
            '--tg-message-in': '#ffffff',
            '--tg-text': '#4a3520',
            '--tg-text-secondary': '#9a7a50',
            '--tg-divider': '#f5e0c0',
            '--tg-online': '#48bb78',
            '--tg-link': '#e67e22',
            '--tg-hover': '#fde8c8',
            '--tg-active-chat': '#e67e22',
            '--tg-input-bg': '#fdf6ec',
            '--tg-header': '#e67e22',
        },
    },
];

export function applyThemePreset(presetId: string) {
    const preset = THEME_PRESETS.find((p) => p.id === presetId);
    if (!preset) return;

    const root = document.documentElement;
    root.classList.toggle('dark', preset.isDark);

    for (const [varName, value] of Object.entries(preset.colors)) {
        root.style.setProperty(varName, value);
    }
}
